asd

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -59,18 +59,33 @@ jobs:
 
       - name: Generate Allure Report with CLI
         run: |
-          ls -R target/allure-results
-          allure generate --single-file target/allure-results --clean -o target/allure-report/${{ github.run_id }} --clean
+          TIMESTAMP=$(date +"%Y%m%d-%H%M%S") 
+          REPORT_DIR="allure-report-$TIMESTAMP" 
+          allure generate --single-file target/allure-results --clean -o target/allure-report/$REPORT_DIR --clean
+          echo "REPORT_DIR=$REPORT_DIR" >> $GITHUB_ENV 
 
-      # Cleanup Old Reports (Keep Last 10)
+      # Cleanup Old Allure Reports (Keep Last 10)
       - name: Cleanup Old Reports (Keep Last 10)
         run: |
           git fetch --depth=1 origin allure-reports
           git checkout allure-reports
-          ls -d */ | sort -r | tail -n +11 | xargs rm -rf
+
+       # Ensure the allure-reports directory exists
+          mkdir -p allure-reports
+          cd allure-reports
+
+        # Remove old reports, but only if there are more than 10
+          if [ $(ls -d */ 2>/dev/null | wc -l) -gt 10 ]; then
+            ls -d */ | sort -r | tail -n +11 | xargs rm -rf
+          else
+            echo "✅ Less than 10 reports exist, skipping cleanup."
+          fi
+
+          cd ..
           git add .
-          git commit -m "Cleanup old reports [skip ci]" || exit 0
+          git commit -m "Cleanup old Allure reports [skip ci]" || exit 0
           git push origin allure-reports
+
 
       # Deploy Allure Report to GitHub Pages
       - name: Deploy Allure Report to GitHub Pages
